### ISSUE TITLE
How to add new environments and generate the corresponding dataset

### ISSUE THREAD

**Issue by Jasonxu1225** [pickxiguapi/Clean-Offline-RLHF#1]
Dear authors, 

This is a good work! 

I have a question about how to add new environments and generate the corresponding dataset? It seems that it only supports for D4RL already exsisted environments.

Many thanks!

**Comment by pickxiguapi** [comment]
Dear Jason, 

Thank you for your interest. Note that Clean-Offline-RLHF repo is the RLHF algorithm codebase, we assume that there is already crowdsourced annotation data here and you can process it into a similar format for training. We open-sourced 30 tasks of labelled data.

As for add new environments and annotate, we recommend checking out the [uni-rlhf annotation platform](https://github.com/pickxiguapi/Uni-RLHF-Platform). If you need a lightweight self-annotation tool and secondary development for research, we recommend [Mini-Uni-RLHF](https://github.com/pickxiguapi/Mini-Uni-RLHF?tab=readme-ov-file#how-to-add-new-datasets), which contains only the core annotation part of the Uni-RLHF platform. 

If you need to script a teacher for preliminary research, we also provide generator scripts in the [fask track](https://github.com/pickxiguapi/Clean-Offline-RLHF/blob/main/fast_track/generate_d4rl_fake_labels.py).

**Comment by Jasonxu1225** [comment]
Got it, many thanks!
