### ISSUE TITLE
About the raw dataset of smarts

### ISSUE THREAD

**Issue by TU2021** [pickxiguapi/Clean-Offline-RLHF#2]
Thank you for opening source for the good and solid work!

It seems that the raw dataset is collected by the author themselves, but I didn't find a pkl file for the raw dataset in the code.  Could you provide the raw dataset pkl or the collection code?

Thanks again for your excellent work!

**Comment by pickxiguapi** [comment]
Sorry for late response. Due to my oversight, I missed uploading the smarts dataset. I will complete it by this Thursday (UTC+8).

**Comment by pickxiguapi** [comment]
Dataset Link: https://drive.google.com/file/d/1_KNH8EziubY2s3r6ySSSzLKnlXexInPp/view?usp=sharing. I will close the issue and feel free to reopen it if you have more questions.
